services:
  shugo-dashboard:
    build: .
    container_name: shugo-tv-prod
    restart: unless-stopped
    networks:
      - shugohub-net
      - npm-net
    depends_on:
      - ticket-api

  ticket-api:
    build: ./ticket-api
    container_name: shugo-ticket-api-prod
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - shugohub-net

networks:
  shugohub-net:
    driver: bridge
  npm-net:
    external: true
    name: nginx-proxy-manager_npm-net
